spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/purchase_data
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  main:
    web-application-type: none
shop:
  receipt: CASH RECEIPT
  markets-id: SUPERMARKET 123
  markets-address: planet Earth
  phone: +375(29) 123-123-12

sales:
  discount: 5
number:
  discount: 10