spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/purchase_data
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  main:
    allow-circular-references: false
server:
  port: 8080
shop:
  receipt: "CASH RECEIPT"
  markets-id: "SUPERMARKET 123"
  markets-address: "planet Earth"
  phone: "+375(29) 123-123-12"

sales:
  sales-discount: 5
  card-discount: 5
  number-discount: 10
download:
  path: C:/Users/Sensationbel/Desktop/receipt.txt